services:
  - type: web
    name: stockholm-sports-bars
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NEXT_PUBLIC_MAPBOX_TOKEN
        sync: false
      - key: NEXT_PUBLIC_GOOGLE_PLACES_API_KEY
        sync: false
      - key: NEXT_PUBLIC_FOOTBALL_API_KEY
        sync: false
